export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";


export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const REGISTER_PRIMARY_REQUEST = "REGISTER_PRIMARY_REQUEST";
export const REGISTER_PRIMARY_SUCCESS = "REGISTER_PRIMARY_SUCCESS";
export const REGISTER_PRIMARY_FAILURE = "REGISTER_PRIMARY_FAILURE";

export const TOKEN_VALIDATE_REQUEST = "TOKEN_VALIDATE_REQUEST";
export const TOKEN_VALIDATE_SUCCESS = "TOKEN_VALIDATE_SUCCESS";
export const TOKEN_VALIDATE_FAILURE = "TOKEN_VALIDATE_FAILURE";

//Seperate one google
export const GOOGLE_LOGIN_REQUEST = "GOOGLE_SIGNUP_REQUEST";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_SIGNUP_SUCCESS";
export const GOOGLE_LOGIN_FAILURE = "GOOGLE_SIGNUP_FAILURE";


//facebook
export const FACEBOOK_LOGIN_REQUEST = "FACEBOOK_SIGNUP_REQUEST";
export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_SIGNUP_SUCCESS";
export const FACEBOOK_LOGIN_FAILURE = "FACEBOOK_SIGNUP_FAILURE";


