export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";


export const GET_BOOKED_DATES_REQUEST = "GET_BOOKED_DATES_REQUEST";
export const GET_BOOKED_DATES_SUCCESS = "GET_BOOKED_DATES_SUCCESS";
export const GET_BOOKED_DATES_FAILURE = "GET_BOOKED_DATES_FAILURE";

export const GET_RECOMENDDATION_REQUEST = "GET_RECOMENDDATION_REQUEST";
export const GET_RECOMENDDATION_SUCCESS = "GET_RECOMENDDATION_SUCCESS";
export const GET_RECOMENDDATION_FAILURE = "GET_RECOMENDDATION_FAILURE";


export const GET_SIMILAR_PROPERTIES_REQUEST = "GET_SIMILAR_PROPERTIES_REQUEST";
export const GET_SIMILAR_PROPERTIES_SUCCESS = "GET_SIMILAR_PROPERTIES_SUCCESS";
export const GET_SIMILAR_PROPERTIES_FAILURE = "GET_SIMILAR_PROPERTIES_FAILURE";

export const ADD_ADULTS = "ADD_ADULTS";
export const SUBTRACT_ADULTS = "SUBTRACT_ADULTS";

export const ADD_CHILDRENS = "ADD_CHILDRENS";
export const SUBTRACT_CHILDRENS = "SUBTRACT_CHILDRENS";

export const ADD_INFANTS = "ADD_INFANTS";
export const SUBTRACT_INFANTS = "SUBTRACT_INFANTS";

export const GET_HOST_INFO_REQUEST = "GET_HOST_INFO_REQUEST";
export const GET_HOST_INFO_SUCCESS = "GET_HOST_INFO_SUCCESS";
export const GET_HOST_INFO_FAILURE = "GET_HOST_INFO_FAILURE";

export const CALCULATE_TOTAL_PRICE = "CALCULATE_TOTAL_PRICE";

export const GET_REVEIW_REQUEST = "GET_REVEIW_REQUEST";
export const GET_REVEIW_SUCCESS = "GET_REVEIW_SUCCESS";
export const GET_REVEIW_FAILURE = "GET_REVEIW_FAILURE";