export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const GET_DATA_PAGEWISE_REQUEST = "GET_DATA_PAGEWISE_REQUEST";
export const GET_DATA_PAGEWISE_SUCCESS = "GET_DATA_PAGEWISE_SUCCESS";
export const GET_DATA_PAGEWISE_FAILURE = "GET_DATA_PAGEWISE_FAILURE";

export const GET_TYPE_OF_PLACE_REQUEST = "GET_TYPE_OF_PLACE_REQUEST";
export const GET_TYPE_OF_PLACE_SUCCESS = "GET_TYPE_OF_PLACE_SUCCESS";
export const GET_TYPE_OF_PLACE_FAILURE = "GET_TYPE_OF_PLACE_FAILURE";

export const GET_AMENITIES_REQUEST = "GET_AMENITIES_REQUEST";
export const GET_AMENITIES_SUCCESS = "GET_AMENITIES_SUCCESS";
export const GET_AMENITIES_FAILURE = "GET_AMENITIES_FAILURE";

export const GET_FACILITIES_REQUEST = "GET_FACILITIES_REQUEST";
export const GET_FACILITIES_SUCCESS = "GET_FACILITIES_SUCCESS";
export const GET_FACILITIES_FAILURE = "GET_FACILITIES_FAILURE";

export const GET_PROPERTY_TYPE_REQUEST = "GET_PROPERTY_TYPE_REQUEST";
export const GET_PROPERTY_TYPE_SUCCESS = "GET_PROPERTY_TYPE_SUCCESS";
export const GET_PROPERTY_TYPE_FAILURE = "GET_PROPERTY_TYPE_FAILURE";

export const CLOSE_CANCELLATION_FLEXIBILITY = "CLOSE_CANCELLATION_FLEXIBILITY";