
export const GET_DETAILS_OF_BOOKING = "GET_DETAILS_OF_BOOKING";

// export const SEND_BOOKING_REQUEST = "SEND_BOOKING_REQUEST";
// export const SEND_BOOKING_SUCECSS = "SEND_BOOKING_SUCECSS";
// export const SEND_BOOKING_FAILURE = "SEND_BOOKING_FAILURE";
